# port values
server:
port: 8080

#database settings
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

#sites
indexing-settings:
  sites:
    - url: https://sendel.ru
      name: Сендел
    - url: https://ipfran.ru
      name: Ипфран
    #- url: https://www.lenta.ru
    #  name: Лента.ру
    #- url: https://www.skillbox.ru
    #  name: Skillbox
    #- url: https://www.playback.ru
    #  name: PlayBack.Ru
  count-page-to-update-site: 20
  storage:
    type: database    # Возможные значения: 'database', 'memory'

#parse-settings
parser-settings:
  user-agent: teumSearchBot
  referrer: http://www.google.com
  timeout: true
  print-error: true

#search settings
searching-settings:
  limit-lemma-frequency: 50
  length-snippet: 60
